#!/bin/bash
# run_featurecounts_local.sh
#
# This script processes each BAM file listed in 'output/bam_list.txt'
# and runs featureCounts on them one by one (sequentially).

# Set the annotation file (generated by generate_gtf.py, for example)
annotation_file="output/modified_for_featurecounts.gtf"

# Create the output directory for featureCounts results if it does not exist
output_dir="./output/featurecounts_output"
mkdir -p "$output_dir"

# Optional: create a logs directory for output
log_dir="$output_dir/logs"
mkdir -p "$log_dir"

# Loop over each line (BAM file) in the list
while IFS= read -r bam_file; do
    if [ ! -f "$bam_file" ]; then
        echo "[Warning] BAM file not found: $bam_file"
        continue
    fi

    # Set the output file name based on the input file name (removing '.bam' extension)
    base_name=$(basename "$bam_file" .bam)
    output_file="$output_dir/featurecounts_${base_name}.txt"

    # Run featureCounts
    echo "Running featureCounts for: $bam_file"
    featureCounts -a "$annotation_file" -o "$output_file" -F GTF -T 1 -p "$bam_file" \
        > "$log_dir/${base_name}.out" 2> "$log_dir/${base_name}.err"

    echo "Processed $bam_file with featureCounts"
done < "output/bam_list.txt"
